'use strict';

const tables = {
  firstTwoTable: {
    Authors: [
      {
        author_name: 'Name_1',
        university: 'University_A',
        date_of_birth: '1980-01-01',
        h_index: 3,
        gender: 'f',
      },
      {
        author_name: 'Name_2',
        university: 'University_B',
        date_of_birth: '1980-01-01',
        h_index: 2,
        gender: 'f',
      },
      {
        author_name: 'Name_3',
        university: 'University_C',
        date_of_birth: '1980-01-01',
        h_index: 10,
        gender: 'f',
      },
      {
        author_name: 'Name_4',
        university: 'University_D',
        date_of_birth: '1980-01-01',
        h_index: 3,
        gender: 'f',
      },
      {
        author_name: 'Name_5',
        university: 'University_A',
        date_of_birth: '1980-01-01',
        h_index: 2,
        gender: 'f',
      },
      {
        author_name: 'Name_6',
        university: 'University_B',
        date_of_birth: '1980-01-01',
        h_index: 1,
        gender: 'f',
      },
      {
        author_name: 'Name_7',
        university: 'University_C',
        date_of_birth: '1980-01-01',
        h_index: 3,
        gender: 'f',
      },
      {
        author_name: 'Name_8',
        university: 'University_D',
        date_of_birth: '1980-01-01',
        h_index: 0,
        gender: 'f',
      },
      {
        author_name: 'Name_9',
        university: 'University_A',
        date_of_birth: '1980-01-01',
        h_index: 1,
        gender: 'm',
      },
      {
        author_name: 'Name_10',
        university: 'University_B',
        date_of_birth: '1980-01-01',
        h_index: 3,
        gender: 'm',
      },
      {
        author_name: 'Name_11',
        university: 'University_C',
        date_of_birth: '1980-01-01',
        h_index: 2,
        gender: 'm',
      },
      {
        author_name: 'Name_12',
        university: 'University_D',
        date_of_birth: '1980-01-01',
        h_index: 1,
        gender: 'm',
      },
      {
        author_name: 'Name_13',
        university: 'University_A',
        date_of_birth: '1980-01-01',
        h_index: 3,
        gender: 'm',
      },
      {
        author_name: 'Name_14',
        university: 'University_B',
        date_of_birth: '1980-01-01',
        h_index: 2,
        gender: 'm',
      },
      {
        author_name: 'Name_15',
        university: 'University_C',
        date_of_birth: '1980-01-01',
        h_index: 3,
        gender: 'm',
      },
    ],
    Research_Papers: [
      {
        paper_title: 'title_1',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_2',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_3',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_4',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_5',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_6',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_7',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_8',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_9',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_10',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_11',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_12',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_13',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_14',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_15',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_16',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_17',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_18',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_19',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_20',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_21',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_22',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_23',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_24',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_25',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_26',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_27',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_28',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_29',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
      {
        paper_title: 'title_30',
        conference: 'conference_name',
        publish_date: '2020-01-01',
      },
    ],
  },
  friendsColumn: [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
  Author_Paper: [
    { author_id: 1, paper_id: 1 },
    { author_id: 1, paper_id: 2 },
    { author_id: 1, paper_id: 3 },
    { author_id: 15, paper_id: 1 },
    { author_id: 2, paper_id: 4 },
    { author_id: 2, paper_id: 5 },
    { author_id: 14, paper_id: 4 },
    { author_id: 3, paper_id: 6 },
    { author_id: 13, paper_id: 6 },
    { author_id: 4, paper_id: 7 },
    { author_id: 4, paper_id: 8 },
    { author_id: 4, paper_id: 9 },
    { author_id: 12, paper_id: 7 },
    { author_id: 5, paper_id: 10 },
    { author_id: 5, paper_id: 11 },
    { author_id: 11, paper_id: 10 },
    { author_id: 6, paper_id: 12 },
    { author_id: 10, paper_id: 12 },
    { author_id: 7, paper_id: 13 },
    { author_id: 7, paper_id: 14 },
    { author_id: 7, paper_id: 15 },
    { author_id: 9, paper_id: 13 },
    { author_id: 10, paper_id: 16 },
    { author_id: 10, paper_id: 17 },
    { author_id: 11, paper_id: 18 },
    { author_id: 13, paper_id: 19 },
    { author_id: 13, paper_id: 20 },
    { author_id: 14, paper_id: 21 },
    { author_id: 3, paper_id: 22 },
    { author_id: 3, paper_id: 23 },
    { author_id: 3, paper_id: 24 },
    { author_id: 3, paper_id: 25 },
    { author_id: 3, paper_id: 26 },
    { author_id: 3, paper_id: 27 },
    { author_id: 3, paper_id: 28 },
    { author_id: 3, paper_id: 29 },
    { author_id: 3, paper_id: 30 },
  ],
};

module.exports = tables;
